### ISSUE TITLE
Prompt for keychain access many times

### ISSUE THREAD

**Issue by boblmartens** [jandamm/wallabag-macos#12]
In order to install, set up, and save a page I am prompted for my admin/keychain password maybe eight times or more.

**Comment by jandamm** [comment]
Noticed this as well. Had the hope it was only my system 😞

The keychain is requested multiple times so the request comes up often. From my understanding it should only come up if I try to read/write outside of the scope of the app.
It seems that there is still some configuration to be done.

**Comment by jandamm** [comment]
@boblmartens I hope I've fixed the issue now. Unfortunately this just adds more hardcoded values into the app.
I hope I can create a released version sometime soon which doesn't require changing bundle identifier (and in this case also the team identifier).

**Comment by boblmartens** [comment]
So I'd need to add my own identifiers in the code to get it working?

**Comment by jandamm** [comment]
Correct and the team identifier which is a bit hard to find.

I'll try to create a release pipeline over the weekend to resolve this testing issue.

**Comment by boblmartens** [comment]
I think I am getting closer. Now I get this error when I try to save the credentials:

`OSStatus error:[-34018] Internal error when a required entitlement isn't present, client has neither application-identifier nor keychain-access-groups entitlements.`

**Comment by jandamm** [comment]
Please run `grep DEVELOPMENT_TEAM Wallabag.xcodeproj/project.pbxproj` in the root of the project folder.
You'll get a few lines like this: `DEVELOPMENT_TEAM = 6N9Z26P656;`. Please copy this value and paste it into `Wallabag/API.swift` on line 5 as `teamIdentifier`.
This should hopefully work.

**Comment by boblmartens** [comment]
I tried both of the dev team identifiers that did not match what you have above and in both cases, I continue to get that error in my terminal.

I will go ahead and see if I can spend some more time troubleshooting with a clean copy of the repo later this week.

**Comment by jandamm** [comment]
Have you changed anything in the entitlements file?
There shouldn't be any change.

I'll upload a 0.9 test build tomorrow which will include this fix.

**Comment by boblmartens** [comment]
Sounds great. Thanks!

**Comment by jandamm** [comment]
@boblmartens, please check out https://github.com/jandamm/wallabag-macos/releases/tag/v0.9.0

**Comment by jandamm** [comment]
Hey @boblmartens,

I've decided to buy a developer account. You can now find the app released here https://apps.apple.com/us/app/wallabag-quicksave/id1621482657 👍

This issue should be fixed now :)
