### ISSUE TITLE
Nothing happening on M1 MBP

### ISSUE THREAD

**Issue by mbirth** [jandamm/wallabag-macos#17]
I've eagerly installed (=copied to "Applications") the app and activated the extension in Safari on my M1 MBP (Late-2020) ... and nothing happened. Where should I find the settings of this extension and the share action?

**Comment by jandamm** [comment]
The Share Extension will be part of the 1.0 Release.

If you open the App first, you'll be prompted to insert your credentials and see a button to show the Safari Extension.

If you directly install the Safari Extension without opening the App first, the App should be opened if the credentials are missing.

If everything went well you should see a `W` IOC  in Safari.

Since I'm not signing this app with a paid developer account, it may be needed to right click the App in Finder, choose `Open` and confirm that you trust this app.

Upon release I'll add a readme including the installation process.

**Comment by boblmartens** [comment]
Downloaded, approved opening, but throws an error right away and crashes. Here is the error:

```
Process:               Wallabag [7936]
Path:                  /Applications/Wallabag.app/Contents/MacOS/Wallabag
Identifier:            Wallabag
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Wallabag [7936]
User ID:               501

Date/Time:             2021-02-03 05:18:34.705 -0600
OS Version:            macOS 11.2 (20D64)
Report Version:        12
Bridge OS Version:     5.2 (18P4346)
Anonymous UUID:        5BA39289-894E-1449-EA7C-7D1C0439A49C

Sleep/Wake UUID:       046848E9-C108-4ACF-A3F7-F048D56C958F

Time Awake Since Boot: 35000 seconds
Time Since Wake:       400 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
```

**Comment by jandamm** [comment]
Alright, I'll undust my old MacBook and test signing.
The crash is also due to incorrect signing.

**Comment by boblmartens** [comment]
Thank you!

**Comment by jandamm** [comment]
Haven't really found a way to sign this application without paying for a official Distribution Certificate.
I know it is possible: [Alacritty](https://github.com/alacritty/alacritty) does it - but it is a Rust project so it doesn't translate 1:1 unfortunately.

I'm not really sure what I can do about it 😒

**Comment by mbirth** [comment]
https://ioscodesigning.com/generating-code-signing-files/

**Comment by jandamm** [comment]
I found a way to not sign the App which lets me execute the app but the safari extension doesn't work...
`usr/bin/xcodebuild -scheme Wallabag -project Wallabag.xcodeproj -configuration Release clean archive -archivePath "build/Wallabag.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO`

**Comment by jandamm** [comment]
> https://ioscodesigning.com/generating-code-signing-files/

@mbirth yes, that's correct.
But you cannot do this if you don't pay Apple $99/year.
Otherwise you can only create development profiles for your devices (and they expire after 1 week).

**Comment by boblmartens** [comment]
Wallabag has an iOS app, so they must have a developer account. Worth asking if you can piggyback off of that?

**Comment by jandamm** [comment]
1. The official [Wallabag App](https://apps.apple.com/us/app/wallabag-2-official/id1170800946) is released by "maxime marinel" which is not an official account.
2. I've asked @nicosomb if he wants to migrate this project to the Wallabag organization. But he hasn't decided yet.

This would probably the easiest way.
I'm not really sure if some sort of fundraising would be sufficient, Safari isn't the most used browser 😉

**Comment by bourvill** [comment]
Hi! I'm maxime marinel aka @bourvill

Notarize process can help you to distribute your app without Apple dev license (only for macOS)

have you try to "notarize" your app before distribution ?

**Comment by jandamm** [comment]
Hi @bourvill thanks for the help.
I've tried notarizing the app via Xcode: `Team "Jan Dammshäuser (Personal Team)" is not enrolled in the Apple Developer Program.`
Do you know of another way to notarize the build?

**Comment by jandamm** [comment]
It is just not possible to release an app with a Safari Extension without an enrolled developer account.
When the app is notarized (which needs enrollment) it is possible to use the extension after entering the password and allowing the extension.

https://developer.apple.com/forums/thread/659029

**Comment by jandamm** [comment]
Hey @mbirth,

I've decided to buy a developer account. You can now find the app released here https://apps.apple.com/us/app/wallabag-quicksave/id1621482657 👍

This issue should be fixed now :)
