### ISSUE TITLE
Not Validating Credentials

### ISSUE THREAD

**Issue by dmin7b5** [jandamm/wallabag-macos#18]
I got the Safari Extension to compile by changing the team and bundle identifier. After compiling and running, it pops up with the form to enter in the Wallabag credentials. After entering in the credentials nothing happens. The logs are below.

Mac mini (2018 / Intel), Big Sur: 11.2, Safari: 14.0.3 (16610.4.3.1.4), XCode: 12.4 (12D4e)

```
2021-02-04 12:17:22.280907-0600 Wallabag[2399:3991153] Metal API Validation Enabled
2021-02-04 12:18:13.845615-0600 Wallabag[2399:3991153] [SafariPlatformSupport] Error loading remote view controller. Error Domain=com.apple.ViewBridge Code=14 "(null)"
2021-02-04 12:18:14.818155-0600 Wallabag[2399:3991153] [SafariPlatformSupport] Error loading remote view controller. Error Domain=com.apple.ViewBridge Code=14 "(null)"
2021-02-04 12:18:18.669816-0600 Wallabag[2399:3994781] [logging] volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags
2021-02-04 12:18:18.670773-0600 Wallabag[2399:3994781] [logging] volume does not support data protection, stripping SQLITE_OPEN_FILEPROTECTION_* flags
OSStatus error:[-34018] Internal error when a required entitlement isn't present, client has neither application-identifier nor keychain-access-groups entitlements.
```

**Comment by jandamm** [comment]
Hi @dmin7b5,
as the last log message states there is an issue with your entitlement file.
Have you used the `main` branch?
Unfortunately there are quite a few identifiers and some have to change while some don't.

I hope I get a valid build out soon (#17). If this doesn't work I'll at least try to ease the manual installation via Xcode by describing the necessary steps.

**Comment by dmin7b5** [comment]
Hi @jandamm,
Yes I was using the `main` branch. Let me know if you decide to document the manual build steps via Xcode and I will help test them for you. Thanks for your work on this!

**Comment by jandamm** [comment]
It is just not possible to release an app with a Safari Extension without an enrolled developer account.
When the app is notarized (which needs enrollment) it is possible to use the extension after entering the password and allowing the extension.

https://developer.apple.com/forums/thread/659029

I might add a description how to install with Xcode later.

**Comment by dmin7b5** [comment]
The extension works great for me using Xcode. I use it every day. The steps I use are: 
1. Make sure to check "Show Develop menu in menu bar" under the "Advanced" tab under Safari preferences. 
2. Click on the "Develop" menu and check "Allow Unsigned Extensions" way at the bottom. 
3. Compile the app in XCode targeting your local Mac. The extension will appear after the build. 
4. Open the Wallabag preference window and fill in your credentials.
5. Enjoy this great extension

**Comment by dmin7b5** [comment]
Closing this issue as there is no way to release the Safari extension without an enrolled developer account. If you have a dev account follow the instructions in the thread to get it to compile and run on your machine.

**Comment by jandamm** [comment]
Thanks I'll add this description + the changes you need to make in Xcode to the Readme.

**Comment by jandamm** [comment]
@dmin7b5 did you need to recompile the App in Xcode?
For iOS Apps you'd need reinstall every one or two weeks. I'm not sure about the Mac.

**Comment by dmin7b5** [comment]
@jandamm You don't have to recompile unless you reboot. Anytime you reboot your computer you do have to go through the same steps and recompile the app on a Mac. But it doesn't take that long to do.

**Comment by dmin7b5** [comment]
@jandamm I just tried compiling the extension using XCode 13.0 to use on Safari 15.0. Everything worked great using the same steps as before. :-)

**Comment by jandamm** [comment]
Thank you for confirming 😊

**Comment by jandamm** [comment]
Hey @dmin7b5,

I've decided to buy a developer account. You can now find the app released here https://apps.apple.com/us/app/wallabag-quicksave/id1621482657 👍

**Comment by dmin7b5** [comment]
@jandamm Is there an option to show the tags screen before saving, or is it just quicksaving URL.

**Comment by jandamm** [comment]
Currently it only is the QuickSave.
I plan to add a Share Extension in the next release since this won't require much time to implement.

I've definitely thought about a tag/metadata viewer but haven't decided yet if or in which timeframe I'll tackle it.
