### ISSUE TITLE
Credentials won't validate

### ISSUE THREAD

**Issue by aniqueta** [jandamm/wallabag-macos#20]
Thanks for a super extension. It's been part of my daily life since it hit the App Store. :) Unfortunately, since updating to [Wallabag 2.6.3](https://github.com/wallabag/wallabag/releases/tag/2.6.3) today, this extension lost the credentials, and it no longer can validate them.

**Comment by aniqueta** [comment]
This appears fixed with [Wallabag 2.6.4](https://github.com/wallabag/wallabag/releases/tag/2.6.4). It wasn't an issue with this extension (although other apps didn't break for some reason). Disregard.

**Comment by jandamm** [comment]
Thanks for the update.

My guess is that the extensions oAuth token needed to be refreshed and this failed.
When the auth fails the token is deleted and the password needs to be entered again.
