### ISSUE TITLE
BUG Feedback - Unable to Use 

### ISSUE THREAD

**Issue by 990355857** [jandamm/wallabag-macos#22]
Hi ：

     I have entered the correct information while using the plugin, but I still cannot log in. There are no error messages, it just asks me to authenticate. What should I do? The same problem occurs on both computers. I also tipped, which makes me quite upset.

**Comment by jandamm** [comment]
Hey my guess would be that it's related to the server using http instead of https.
Would it be possible to add https via https://letsencrypt.org/ or similar?

I'll release a version with improved error messages when I come around to it.

**Comment by 990355857** [comment]
Hi&nbsp;


Thank you for your reply.&nbsp;



I tried using https, but the problem is still that I can't authenticate. I look forward to your help. Thank you.





振兴中华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jandamm/wallabag-macos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月3日(星期天) 下午5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jandamm/wallabag-macos] BUG Feedback - Unable to Use  (Issue #22)





 
Hey my guess would be that it's related to the server using http instead of https.
 Would it be possible to add https via https://letsencrypt.org/ or similar?
 
I'll release a version with improved error messages when I come around to it.

**Comment by jandamm** [comment]
At least in the browser I wasn't able to connect to the server via https. The server needs to be configured to accept https.

Would you be able to create a demo account at https://wallabag.it? (There's a free 14 day trial)
If you'd be able to authenticate there it's an issue with your server and not on your machine.

If it's the http issue I need to check whether I can get the app to allow http connections. Apple is restrictive in this area.

**Comment by 990355857** [comment]
Thank you for your reply！

I just understood what you meant. Currently, I only have http, and I haven't applied for https yet. I am currently in the process of applying for https.

Waiting for your good news - successfully applied for HTTP authentication.

**Comment by jandamm** [comment]
Thanks.
I hope I fixed your issue in `v2024.3` which will be released soon.
If it isn't fixed you'll at least get an popup with the error provided by the server/URLSession.

**Comment by jandamm** [comment]
It's live, @990355857 👍

**Comment by 990355857** [comment]
Thank you very much for your help.

**Comment by 990355857** [comment]
Hi When will the update be available for download on Safari?

**Comment by jandamm** [comment]
It might take up to 24h to be distributed worldwide.
But you should already be able to see the update in the App Store.

**Comment by 990355857** [comment]
Although the prompt verification was successful, the plugin cannot be used. Clicking the plugin button did not result in the article being captured on wallabag.

**Comment by jandamm** [comment]
That is strange.
You should see a short red badge on the icon when saving fails.
I also allowed the extension to connect via http - so this shouldn't be the issue.

**Comment by jandamm** [comment]
@990355857 is the server your own server?
If so you could create a temporary account for me so that I could debug the extension.

**Comment by 990355857** [comment]
It's working.




振兴中华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jandamm/wallabag-macos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月12日(星期二) 晚上8:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jandamm/wallabag-macos] BUG Feedback - Unable to Use  (Issue #22)





 
@990355857 is the server your own server?
 If so you could create a temporary account for me so that I could debug the extension.

**Comment by jandamm** [comment]
Thank you for verifying!
