### ISSUE TITLE
Add Confirmation/Errors

### ISSUE THREAD

**Issue by jandamm** [jandamm/wallabag-macos#3]
When a url couldn't be added there should be some kind of visual feedback provided by the Safari Extension.
A confirmation/progress display would be nice as well.

**Comment by boblmartens** [comment]
I agree, a confirmation when it is saved would be great as well.

**Comment by jandamm** [comment]
For the `QuickSave` Extension I've added a badge to the icon:
`...` for loading and `Error`/`E404` for errors (where `404` is the http status code) - they automatically disappear after three seconds.
Optionally I've added a confirmation message (`Ok`) which can be activated from a settings panel I might add in the future.

What do you think about this?

**Comment by boblmartens** [comment]
Are you going to be tagging releases in the near future? I am more than happy to play around and test any releases you would like.

**Comment by jandamm** [comment]
My plan is to add the features of issues 1-3 and close any bugs that occur.
Then I would like to migrate it to the wallabag organization and release it to the AppStore.

If you want to test this version, checkout `Add-visual-feedback-when-saving-fails` and run via Xcode.
When I create a PR I consider the feature done.
