### ISSUE TITLE
Button to close app and open Safari did not work

### ISSUE THREAD

**Issue by boblmartens** [jandamm/wallabag-macos#4]
When I clicked the button to close the app and open Safari, it did not work for me. I fully understand this could be a build error on my side of things.

**Comment by jandamm** [comment]
@boblmartens to get things compiling you had to change the unique bundle identifier from `de.jandamm.ent.Wallabag` to something else.
Please change `Wallabag/ViewController.swift` line 14 accordingly. This should fix this issue 👍

**Comment by boblmartens** [comment]
I will dig into just that. Thanks!

**Comment by jandamm** [comment]
Have you been able to solve this issue?
When you now pull `main` again it should work without changing a file manually.

**Comment by boblmartens** [comment]
I will try and take a look at this tomorrow. Thank you!

**Comment by boblmartens** [comment]
Worked like a charm after pulling down main.

**Comment by jandamm** [comment]
Okay, I'll close it then.
